### ISSUE TITLE
Please state actual Project status

### ISSUE THREAD

**Issue by janbrohl** [benjaoming/pipsec#2]
https://pypi.python.org/pypi/pipsec says this package is beta-status. But as there actually is no working code in this Repo except for setup.py please state that this package actually does not do anything yet. To my understanding this means even stating alpha-status would be too much at this moment.

**Comment by benjaoming** [comment]
Yes, you are right, as I explained in #1, this is because of a hurried publishing of pytosquatting.org

**Comment by benjaoming** [comment]
This is done now, thanks for the concern and sorry about mislabeling
